# Generated by Django 3.2.6 on 2021-10-11 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_auto_20211010_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_notifications',
            name='Notification_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 11, 11, 57, 40, 901262)),
        ),
        migrations.AlterField(
            model_name='vendor_notifications',
            name='Notification_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 11, 11, 57, 40, 901262)),
        ),
    ]
