# Generated by Django 3.2.5 on 2021-09-28 11:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0017_auto_20210928_1707'),
        ('checkout', '0015_auto_20210928_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_table',
            name='Order_Date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 28, 17, 7, 53, 919645)),
        ),
        migrations.AlterField(
            model_name='order_table',
            name='Order_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 28, 17, 7, 53, 919645)),
        ),
        migrations.AlterField(
            model_name='order_table',
            name='Paid_Date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 28, 17, 7, 53, 919645)),
        ),
        migrations.AlterField(
            model_name='order_table',
            name='Paid_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 28, 17, 7, 53, 919645)),
        ),
        migrations.AlterField(
            model_name='order_table_2',
            name='Order_Date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 28, 17, 7, 53, 920642)),
        ),
        migrations.AlterField(
            model_name='order_table_logs',
            name='logs_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 28, 17, 7, 53, 920642)),
        ),
        migrations.CreateModel(
            name='order_table_3_logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logs_status', models.TextField(blank=True, null=True)),
                ('logs_time', models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 28, 17, 7, 53, 931037))),
                ('order_table_3', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='checkout.order_table_3')),
                ('staff_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_1.staff_access')),
            ],
            options={
                'verbose_name_plural': 'Order Table 3 Logs',
            },
        ),
    ]
