# Generated by Django 3.2.6 on 2021-10-10 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_benner',
            name='benner',
            field=models.ImageField(blank=True, help_text='Choose Only .jpg, .jpeg, .png, .webp files PLease..', null=True, upload_to='Home_benner/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='home_bottom_benner',
            name='home_bottom_benner',
            field=models.ImageField(blank=True, help_text='Choose Only .jpg, .jpeg, .png, .webp files PLease..', null=True, upload_to='home_bottom_benner/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='home_little_benner',
            name='benner',
            field=models.ImageField(blank=True, help_text='Choose Only .jpg, .jpeg, .png, .webp files PLease..', null=True, upload_to='home_little_benner/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='home_side_benner',
            name='home_side_benner',
            field=models.ImageField(blank=True, help_text='Choose Only .jpg, .jpeg, .png, .webp files PLease..', null=True, upload_to='home_bottom_benner/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='shop_now_page_benner',
            name='Shop_now_page_benner',
            field=models.ImageField(blank=True, help_text='Choose Only .jpg, .jpeg, .png, .webp files PLease..', null=True, upload_to='Shop_now_page_benner/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'webp'])]),
        ),
    ]
