# Generated by Django 3.2.6 on 2021-09-27 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_dashboard_app', '0010_alter_vendor_registration_table_join_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_registration_table',
            name='vendor_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendor_registration_table',
            name='join_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 27, 13, 54, 58, 652232)),
        ),
    ]
