# Generated by Django 3.2.6 on 2021-09-27 09:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_dashboard_app', '0011_auto_20210927_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_registration_table',
            name='join_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 27, 15, 11, 59, 300993)),
        ),
        migrations.CreateModel(
            name='vendor_PO_NUMBER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_Number', models.IntegerField()),
                ('Vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_dashboard_app.vendor_registration_table')),
            ],
        ),
    ]
