# Generated by Django 3.2.6 on 2021-09-27 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_dashboard_app', '0012_auto_20210927_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor_po_number',
            old_name='Account_Number',
            new_name='Vendor_po_Number',
        ),
        migrations.AlterField(
            model_name='vendor_registration_table',
            name='join_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 27, 15, 28, 30, 178441)),
        ),
    ]
