# Generated by Django 3.2.5 on 2021-09-28 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_dashboard_app', '0013_auto_20210927_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_registration_table',
            name='join_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 28, 12, 4, 31, 710202)),
        ),
    ]
