# Generated by Django 3.2.6 on 2021-10-02 05:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_dashboard_app', '0023_alter_vendor_registration_table_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_payment_info',
            name='SSL_operator',
            field=models.CharField(blank=True, choices=[('', ''), ('Bkash', 'Bkash'), ('Nogod', 'Nogod')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vendor_registration_table',
            name='join_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 2, 11, 31, 34, 781461)),
        ),
    ]
