# Generated by Django 3.2.6 on 2021-10-02 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_dashboard_app', '0024_auto_20211002_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_payment_info',
            name='SSL_operator',
            field=models.CharField(blank=True, choices=[('Bkash', 'Bkash'), ('Nogod', 'Nogod')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vendor_registration_table',
            name='join_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 2, 11, 35, 17, 1011)),
        ),
    ]
