# Generated by Django 3.2.6 on 2021-10-02 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_dashboard_app', '0025_auto_20211002_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_registration_table',
            name='join_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 2, 8, 15, 47, 434157)),
        ),
    ]
